object frmBack: TfrmBack
  Left = 0
  Top = 0
  AlphaBlend = True
  AlphaBlendValue = 100
  BorderIcons = []
  BorderStyle = bsNone
  Caption = 'frmBack'
  ClientHeight = 520
  ClientWidth = 845
  Color = clBlack
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  OnClose = FormClose
  OnHide = FormHide
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
end
